var provincias = new Array('San José', 'Alajuela', 'Cartago', 'Heredia', 'Puntarenas', 'Guanacaste', 'Limón');
/*CANTONES*/
cantones = new Array();
distritos = new Array();
cantones[0] = new Array(
		'San José',
		'Escazú',
		'Desamparados',
		'Puriscal',
		'Tarrazú',
		'Aserrí',
		'Mora',
		'Goicoechea',
		'Santa Ana',
		'Alajuelita',
		'Vásquez de Coronado',
		'Acosta',
		'Tibás',
		'Moravia',
		'Montes de Oca',
		'Turrubares',
		'Dota',
		'Curridabat',
		'Pérez Zeledón',
		'León Cortés');
cantones[1] = new Array (
		'Alajuela',
		'San Ramón',
		'Grecia',
		'San Mateo',
		'Atenas',
		'Naranjo',
		'Palmares',
		'Poás',
		'Orotina',
		'San Carlos',
		'Zarcero',
		'Valverde Vega',
		'Upala',
		'Los Chiles',
		'Guatuso'
		);
cantones[2] = new Array (
		'Cartago',
		'Paraíso',
		'La Unión',
		'Jiménez',
		'Turrialba',
		'Alvarado',
		'Oreamuno',
		'El Guarco'		
		);
cantones[3] = new Array (
		'Heredia',
		'Barva',
		'Santo Domingo',
		'Santa Bárbara',
		'San Rafael',
		'San Isidro',
		'Belén',
		'Flores',
		'San Pablo',
		'Sarapiquí'	
		);
cantones[4] = new Array (
		'Puntarenas',
		'Esparza',
		'Buenos Aires',
		'Montes de Oro',
		'Osa',
		'Aguirre',
		'Golfito',
		'Coto Brus',
		'Parrita',
		'Corredores',
		'Garabito'
		);
cantones[5] = new Array (
		'Liberia',
		'Nicoya',
		'Santa Cruz',
		'Bagaces',
		'Carrillo',
		'Cañas',
		'Abangares',
		'Tilarán',
		'Nandayure',
		'La Cruz',
		'Hojancha'
		);
cantones[6] = new Array (
		'Limón',
		'Pococí',
		'Siquirres',
		'Talamanca',
		'Matina',
		'Guácimo'
		);
/*DISTRITOS*/
/*San Jose*/
distritos[0] = [
	['Carmen',
	'Merced',
	'Hospital',
	'Catedral',
	'Zapote',
	'San Francisco de Dos Ríos',
	'Uruca',
	'Mata Redonda',
	'Pavas',
	'Hatillo',
	'San Sebastián',
	'Santa Ana',
	'Salitral',
	'Pozos',
	'Uruca',
	'Piedades',
	'Brasil'
	],
	['Escazú',
	'San Antonio',
	'San Rafael'
	],[
	'Desamparados',
	'San Miguel',
	'San Juan de Dios',
	'San Rafael Arriba',
	'San Antonio',
	'Frailes',
	'Patarrá',
	'San Cristóbal',
	'Rosario',
	'Damas',
	'San Rafael Abajo',
	'Gravilias',
	'Los Guido'
	],[
	'Santiago',
	'Mercedes Sur',
	'Barbacoas',
	'Grifo Alto',
	'San Rafael',
	'Candelarita',
	'Desamparaditos',
	'San Antonio',
	'Chires'
	],[
	'San Marcos',
	'San Lorenzo',
	'San Carlos'
	],[
	'Aserrí',
	'Tarbaca',
	'Vuelta de Jorco',
	'San Gabriel',
	'Legua',
	'Monterrey',
	'Salitrillos'
	],[
	'Ciudad Colón',
	'Guayabo',
	'Tabarcia',
	'Piedras Negras',
	'Picagres',
	'Jaris'
	],[
	'Guadalupe',
	'San Francisco',
	'Calle Blancos',
	'Mata de Plátano',
	'Ipís',
	'Rancho Redondo',
	'Purral'
	],[
	'Santa Ana',
	'Salitral',
	'Pozos',
	'Uruca',
	'Piedades',
	'Brasil'
	],[
	'Alajuelita',
	'San Josecito',
	'San Antonio',
	'Concepción',
	'San Felipe'
	],[
	'San Isidro',
	'San Rafael',
	'Dulce Nombre de Jesús',
	'Patalillo',
	'Cascajal'
	],[
	'San Ignacio',
	'Guaitil',
	'Palmichal',
	'Cangrejal',
	'Sabanillas'
	],[
	'San Juan',
	'Cinco Esquinas',
	'Anselmo Llorente',
	'León XIII',
	'Colima'
	],[
	'San Vicente',
	'San Jerónimo',
	'Trinidad'
	],[
	'San Pedro',
	'Sabanilla',
	'Mercedes',
	'San Rafael'
	],[
	'San Pablo',
	'San Pedro',
	'San Juan de Mata',
	'San Luis',
	'Carara'
	],[
	'Santa María',
	'Jardín',
	'Copey'
	],[
	'Curridabat',
	'Granadilla',
	'Sánchez',
	'Tirrases'
	],[
	'San Isidro de El General',
	'El General',
	'Daniel Flores',
	'Rivas',
	'San Pedro',
	'Platanares',
	'Pejibaye',
	'Cajón',
	'Barú',
	'Río Nuevo',
	'Páramo'
	],[
	'San Pablo',
	'San Andrés',
	'Llano Bonito',
	'San Isidro',
	'Santa Cruz',
	'San Antonio'
	]
];
/*Alajuela*/
distritos[1] = [
['Alajuela',
'San José',
'Carrizal',
'San Antonio',
'Guácima',
'San Isidro',
'Sabanilla',
'San Rafael',
'Río Segundo',
'Desamparados',
'Turrúcares',
'Tambor',
'Garita',
'Sarapiquí'],['San Ramón',
'Santiago',
'San Juan',
'Piedades Norte',
'Piedades Sur',
'San Rafael',
'San Isidro',
'Ángeles',
'Alfaro',
'Volio',
'Concepción',
'Zapotal',
'Peñas Blancas'],[
'Grecia',
'San Isidro',
'San José',
'San Roque',
'Tacares',
'Río Cuarto',
'Puente de Piedra',
'Bolívar'],[
'San Mateo',
'Desmonte',
'Jesús María'
],['Atenas',
'Jesús',
'Mercedes',
'San Isidro',
'Concepción',
'San José',
'Santa Eulalia',
'Escobal'],['Naranjo',
'San Miguel',
'San José',
'Cirrí Sur',
'San Jerónimo',
'San Juan',
'El Rosario',
'Palmitos'],['Palmares',
'Zaragoza',
'Buenos Aires',
'Santiago',
'Candelaria',
'Esquipulas',
'La Granja'],['San Pedro',
'San Juan',
'San Rafael',
'Carrillos',
'Sabana Redonda'],['Orotina',
'Mastate',
'Hacienda Vieja',
'Coyolar',
'La Ceiba'],[
'Quesada',
'Florencia',
'Buenavista',
'Aguas Zarcas',
'Venecia',
'Pital',
'La Fortuna',
'La Tigra',
'La Palmera',
'Venado',
'Cutris',
'Monterrey',
'Pocosol'],[
'Zarcero',
'Laguna',
'Tapezco',
'Guadalupe',
'Palmira',
'Zapote',
'Brisas'],['Sarchí Norte',
'Sarchí Sur',
'Toro Amarillo',
'San Pedro',
'Rodríguez'],['Upala',
'Aguas Claras',
'San José (Pizote)',
'Bijagua',
'Delicias',
'Dos Ríos',
'Yolillal'],['Los Chiles',
'Caño Negro',
'El Amparo',
'San Jorge'],['San Rafael',
'Buenavista',
'Cote',
'Katira']
];
/*Cartago*/
distritos[2] = [['Oriental',
'Occidental',
'Carmen',
'San Nicolás',
'Agua Caliente (San Francisco)',
'Guadalupe (Arenilla)',
'Corralillo',
'Tierra Blanca',
'Dulce Nombre',
'Llano Grande',
'Quebradilla'],['Paraíso',	
'Santiago de Paraíso',	
'Orosi',	
'Cachí',	
'Llanos de Santa Lucía'],['Tres Ríos',
'San Diego',
'San Juan',
'San Rafael',
'Concepción',
'Dulce Nombre',
'San Ramón',
'Río Azul'],['Juan Viñas',
'Tucurrique',
'Pejibaye'],['Turrialba',
'La Suiza',
'Peralta',
'Santa Cruz',
'Santa Teresita',
'Pavones',
'Tuis',
'Tayutic',
'Santa Rosa',
'Tres Equis',
'La Isabel',
'Chirripó'],['Distrito Alvarado',
'Pacayas',
'Cervantes',
'Capellades'],['San Rafael',
'Cot',
'Potrero Cerrado',
'Cipreses',
'Santa Rosa'],['Tejar',
'San Isidro',
'Tobosi',
'Patio de Agua']
];
distritos[3] = [
['Heredia',	
'Mercedes',	
'San Francisco',	
'Ulloa',	
'Varablanca'],['Barva',	
'San Pedro',	
'San Pablo',	
'San Roque',	
'Santa Lucía',	
'San José de la Montaña'],['Santo Domingo',
'San Vicente',
'San Miguel',
'Paracito',
'Santo Tomás',
'Santa Rosa',
'Tures',
'Pará'],['Santa Bárbara',	
'San Pedro',	
'San Juan',	
'Jesús',	
'Santo Domingo',	
'Purabá'],['San Rafael',
'San Josecito',
'Santiago',
'Ángeles',
'Concepción'],['San Isidro',
'San José',
'Concepción',
'San Francisco'],['San Antonio',
'La Ribera',
'La Asunción'],['San Joaquín',
'Barrantes',
'Llorente'],['San Pablo',	
'Rincón de Sabanilla'],['Puerto Viejo',	
'La Virgen',	
'Las Horquetas',	
'Llanuras del Gaspar',	
'Cureña']
];
distritos[4] = [
['Puntarenas',
'Pitahaya',
'Chomes',
'Lepanto',
'Paquera',
'Manzanillo',
'Guacimal',
'Barranca',
'Monteverde',
'Isla del Coco',
'Cóbano',
'Chacarita',
'Chira',
'Acapulco',
'El Roble',
'Arancibia'],['Espíritu Santo',	
'San Juan Grande',	
'Macacona',
'San Rafael',	
'San Jerónimo'],['Buenos Aires',	
'Volcán',
'Potrero Grande',	
'Boruca',	
'Pilas',
'Colinas',	
'Chánguena',	
'Biolley',	
'Brunka'	],['Miramar',
'La Unión',
'San Isidro'],['Puerto Cortés',	
'Palmar',	
'Sierpe',	
'Bahía Ballena',	
'Piedras Blancas'],['Quepos',
'Savegre',
'Naranjito'],['Golfito',	
'Puerto Jiménez',	
'Guaycará',	
'Pavón'],['San Vito',
'Sabalito',
'Aguabuena',
'Limoncito',
'Pittier'],
['Parrita'],
['Corredor',
'La Cuesta',
'Paso Canoas',
'Laurel'],
['Jacó',
'Tárcoles']
];
distritos[5] = [
['Liberia',
'Cañas Dulces',
'Mayorga',
'Nacascolo',
'Curubandé'],['Nicoya',
'Mansión',
'San Antonio',
'Quebrada Honda',
'Sámara',
'Nosara',
'Belén de Nosarita'],['Santa Cruz',
'Bolsón',
'Veintisiete de Abril',
'Tempate',
'Cartagena',
'Cuajiniquil',
'Diriá',
'Cabo Velas',
'Tamarindo'],['Bagaces',
'La Fortuna',
'Mogote',
'Río Naranjo'],['Filadelfia',
'Palmira',
'Sardinal',
'Belén'],['Cañas',
'Palmira',
'San Miguel',
'Bebedero',
'Porozal'],['Las Juntas',
'Sierra',
'San Juan',
'Colorado'],['Tilarán',
'Quebrada Grande',
'Tronadora',
'Santa Rosa',
'Líbano',
'Tierras Morenas',
'Arenal'],['Carmona',
'Santa Rita',
'Zapotal',
'San Pablo',
'Porvenir',
'Bejuco'],['La Cruz',
'Santa Cecilia',
'La Garita',
'Santa Elena'],['Hojancha',
'Monte Romo',
'Puerto Carrillo',
'Huacas']
];
distritos[6] = [
['Limón',
'Valle La Estrella',
'Río Blanco',
'Matama'],['Guápiles',
'Jiménez',
'Rita',
'Roxana',
'Cariari',
'Colorado'],['Siquirres',
'Pacuarito',
'Florida',
'Germania',
'Cairo',
'Alegría'],['Bratsi',
'Sixaola',
'Cahuita',
'Telire'],['Matina',
'Batán',
'Carrandi'],['Guácimo',
'Mercedes',
'Pocora',
'Río Jiménez',
'Duacarí']
];